#!/bin/bash

VER="2.9.5"

# https://stackoverflow.com/questions/17056374/how-can-we-check-if-string-is-a-version-number-or-not
if [[ $DOCKER_TAG =~ ^[0-9]+(\.[0-9]+){1,3}$ ]]
then
  VER="$DOCKER_TAG"
fi

docker build --build-arg ANSIBLE_VERSION="$VER" -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .